### ISSUE TITLE
Problem when using two "small words" with dots

### ISSUE THREAD

**Issue by mauro-oto** [granth/titleize#12]
Hey, 

I am using the `titleize` gem via the Jekyll plugin https://github.com/ryanburnette/jekyll-titleize. I was trying to create a blog post with the title `Spy vs. Double vs. Instance Double` and getting this exception: 

```
➜  blog git:(spy-or-double-or-instance-double) ✗ be jekyll build --trace
Configuration file: /Users/mauro-oto/Projects/ombulabs.com/blog/_config.yml
            Source: /Users/mauro-oto/Projects/ombulabs.com/blog
       Destination: /Users/mauro-oto/Projects/ombulabs.com/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: no implicit conversion of nil into String in _layouts/default.html
/Users/mauro-oto/.rvm/gems/ruby-2.2.3@ombulabs.com/gems/titleize-1.4.0/lib/titleize.rb:65:in `+': no implicit conversion of nil into String (TypeError)
    from /Users/mauro-oto/.rvm/gems/ruby-2.2.3@ombulabs.com/gems/titleize-1.4.0/lib/titleize.rb:65:in `block in phrases'
    from /Users/mauro-oto/.rvm/gems/ruby-2.2.3@ombulabs.com/gems/titleize-1.4.0/lib/titleize.rb:63:in `each'
    from /Users/mauro-oto/.rvm/gems/ruby-2.2.3@ombulabs.com/gems/titleize-1.4.0/lib/titleize.rb:63:in `each_with_index'
    from /Users/mauro-oto/.rvm/gems/ruby-2.2.3@ombulabs.com/gems/titleize-1.4.0/lib/titleize.rb:63:in `phrases'
    from /Users/mauro-oto/.rvm/gems/ruby-2.2.3@ombulabs.com/gems/titleize-1.4.0/lib/titleize.rb:24:in `titleize'
    from /Users/mauro-oto/.rvm/gems/ruby-2.2.3@ombulabs.com/gems/titleize-1.4.0/lib/titleize.rb:88:in `titleize'
    from /Users/mauro-oto/Projects/ombulabs.com/blog/_plugins/titleize.rb:8:in `titleize'
```

For some reason the operation done on the `vs.` word (contained in `SMALL_WORDS`) is trying to add an empty string to `nil`, which results in this exception. You can reproduce it using the following example: 

```
➜  blog git:(spy-or-double-or-instance-double) ✗ irb
2.2.3 :001 > require "titleize"
 => true
2.2.3 :002 > "hello. world.".titleize
 => "Hello. World."
2.2.3 :003 > "Spy vs. Double vs. Instance Double".titleize
TypeError: no implicit conversion of nil into String
```

Thanks for the gem!

**Comment by granth** [comment]
Thanks for the clear bug report! I see the problem is in the awkward handling of "vs." and "v." when splitting on punctuation. I'm on vacation this week but I'll try to fix it soon.
